### ISSUE TITLE
Release 0.7.3 brings typing errors to projects which use `aioresponses`

### ISSUE THREAD

**Issue by marcinsulikowski** [pnuckowski/aioresponses#202]
After upgrading aioresponses from 0.7.2 to 0.7.3 in a project which uses the library in its tests and uses `mypy --strict` for type checking, linting started to fail with the following errors:

    tests/test_xxxx.py:53: error: Call to untyped function "clear" in typed context
    tests/test_yyyy.py:447: error: Call to untyped function "clear" in typed context
    tests/zzzz/test_zzzz.py:115: error: Call to untyped function "aioresponses" in typed context

This is because, unlike 0.7.2, the 0.7.3 release ships with the `py.typed` marker (see: #193) which tells `mypy` that the library is typed and that that `mypy` can type check calls to the library's functions. which `mypy` didn't do in 0.7.2. However, some of the public functions provided by the library are not typed, which introduces the errors listed above.
