### ISSUE TITLE
"TypeError: RequestInfo.__new__() missing 1 required positional argument: 'real_url'" after upgrading aiohttp to 3.11.0.

### ISSUE THREAD

**Issue by cdessez** [pnuckowski/aioresponses#263]
`aiohttp` just released [v3.11.0](https://github.com/aio-libs/aiohttp/releases/tag/v3.11.0).

Trying to use `aioresponses` together with `aiohttp==3.11.0` leads to the following failure:

```
>               async with session.get(url) as response:

scratch_164.py:12: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
.../lib/python3.10/site-packages/aiohttp/client.py:1418: in __aenter__
    self._resp: _RetType = await self._coro
.../lib/python3.10/unittest/mock.py:2217: in _execute_mock_call
    result = await effect(*args, **kwargs)
.../lib/python3.10/site-packages/aioresponses/core.py:512: in _request_mock
    response = await self.match(method, url, **kwargs)
.../lib/python3.10/site-packages/aioresponses/core.py:456: in match
    response_or_exc = await matcher.build_response(
.../lib/python3.10/site-packages/aioresponses/core.py:202: in build_response
    resp = self._build_response(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <aioresponses.core.RequestMatch object at 0x1459d08e0>
url = URL('http://example.com'), method = 'get', request_headers = {}
status = 200, body = b'Yo!', content_type = 'application/json', payload = None
headers = None, response_class = <class 'aiohttp.client_reqrep.ClientResponse'>
reason = 'OK'

    def _build_response(self, url: 'Union[URL, str]',
                        method: str = hdrs.METH_GET,
                        request_headers: Optional[Dict] = None,
                        status: int = 200,
                        body: Union[str, bytes] = '',
                        content_type: str = 'application/json',
                        payload: Optional[Dict] = None,
                        headers: Optional[Dict] = None,
                        response_class: Optional[Type[ClientResponse]] = None,
                        reason: Optional[str] = None) -> ClientResponse:
        if response_class is None:
            response_class = ClientResponse
        if payload is not None:
            body = json.dumps(payload)
        if not isinstance(body, bytes):
            body = str.encode(body)
        if request_headers is None:
            request_headers = {}
        loop = Mock()
        loop.get_debug = Mock()
        loop.get_debug.return_value = True
        kwargs = {}  # type: Dict[str, Any]
>       kwargs['request_info'] = RequestInfo(
            url=url,
            method=method,
            headers=CIMultiDictProxy(CIMultiDict(**request_headers)),
        )
E       TypeError: RequestInfo.__new__() missing 1 required positional argument: 'real_url'
```

This can be reproduced with the following minimal reproducer:
```python
import aiohttp
from aioresponses import aioresponses
import pytest


@pytest.mark.asyncio()
async def test_aiohttp_3_11_0():
    with aioresponses() as aiohttp_mock:
        url = "http://example.com"
        aiohttp_mock.get(url, status=200, body="Yo!")
        async with aiohttp.ClientSession() as session:
            async with session.get(url) as response:
                body = await response.text()
                print(body)
```
This test leads to the above failure on `aiohttp==3.11.0`, but passes on `aiohttp==3.10.11`.

**Comment by bartfeenstra** [comment]
I raised this with aiohttp: https://github.com/aio-libs/aiohttp/issues/9866

**Comment by bdraco** [comment]
Fix is here https://github.com/pnuckowski/aioresponses/pull/262

**Comment by cdessez** [comment]
This is now resolved. Fixed by both:
* #262 being merged
* `aiohttp` releasing `3.11.1` with https://github.com/aio-libs/aiohttp/pull/9873
